### ISSUE TITLE
Can not start ttn-gateway

### ISSUE THREAD

**Issue by flemming-pr** [mockingbirdconsulting/ttn-pkt-fwd-resin-setup#1]
I have set up a gateway with resin.io and used your repo.

But I always get some errors: 

[/etc/systemd/system/ttn-gateway.service:8] Failed to parse usec_t value, ignoring: infinity
[/etc/systemd/system/ttn-gateway.service:10] Failed to parse usec_t value, ignoring: infinity

And also the internal ttn-gateway service won't start causing this error:
ERROR The program ended following a failure    error=Failed to start concentrator

I use a simple backplane and use pin 22 as reset pin. Sometimes the gateway will work properly but most of the time these both errors will appear.

My concentrator board is an iC880A-SPI concentrator board
I'm powering everthing over a supply with 4A.

i hope you can help me.

**Comment by proffalken** [comment]
Hello!

We've stopped deploying using Resin and instead we're using github.com/brocaar/lora-gateway-os and a custom deployment of mender.io.

We're also deploying almost exclusively to LoRaServer.io installations rather than TTN/TTI these days, so lora-gateway-os is a better fit for our setup.

As a result, I'm not too sure where we can help (other than to archive this repo) as we don't even have the test rig for this around anymore unfortunately.
